// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// The request message for
/// [RegistrationService.ListEndpoints][google.cloud.servicedirectory.v1.RegistrationService.ListEndpoints].
///
/// [google.cloud.servicedirectory.v1.RegistrationService.ListEndpoints]: <doc:RegistrationServiceClient/listEndpoints(request:options:)>
public struct ListEndpointsRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The resource name of the service whose endpoints you'd like to
  /// list.
  public var parent: Swift.String = Swift.String()

  /// Optional. The maximum number of items to return.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// Optional. The next_page_token value returned from a previous List request,
  /// if any.
  public var pageToken: Swift.String = Swift.String()

  /// Optional. The filter to list results by.
  ///
  /// General `filter` string syntax:
  /// `<field> <operator> <value> (<logical connector>)`
  ///
  /// *   `<field>` can be `name`, `address`, `port`, or `annotations.<key>` for
  ///      map field
  /// *   `<operator>` can be `<`, `>`, `<=`, `>=`, `!=`, `=`, `:`. Of which `:`
  ///     means `HAS`, and is roughly the same as `=`
  /// *   `<value>` must be the same data type as field
  /// *   `<logical connector>` can be `AND`, `OR`, `NOT`
  ///
  /// Examples of valid filters:
  ///
  /// *   `annotations.owner` returns endpoints that have a annotation with the
  ///     key `owner`, this is the same as `annotations:owner`
  /// *   `annotations.protocol=gRPC` returns endpoints that have key/value
  ///     `protocol=gRPC`
  /// *   `address=192.108.1.105` returns endpoints that have this address
  /// *   `port>8080` returns endpoints that have port number larger than 8080
  /// *
  /// `name>projects/my-project/locations/us-east1/namespaces/my-namespace/services/my-service/endpoints/endpoint-c`
  ///     returns endpoints that have name that is alphabetically later than the
  ///     string, so "endpoint-e" is returned but "endpoint-a" is not
  /// *   `annotations.owner!=sd AND annotations.foo=bar` returns endpoints that
  ///     have `owner` in annotation key but value is not `sd` AND have
  ///     key/value `foo=bar`
  /// *   `doesnotexist.foo=bar` returns an empty list. Note that endpoint
  ///     doesn't have a field called "doesnotexist". Since the filter does not
  ///     match any endpoints, it returns no results
  ///
  /// For more information about filtering, see
  /// [API Filtering](https://aip.dev/160).
  public var filter: Swift.String = Swift.String()

  /// Optional. The order to list results by.
  ///
  /// General `order_by` string syntax: `<field> (<asc|desc>) (,)`
  ///
  /// *   `<field>` allows values: `name`, `address`, `port`
  /// *   `<asc|desc>` ascending or descending order by `<field>`. If this is
  ///     left blank, `asc` is used
  ///
  /// Note that an empty `order_by` string results in default order, which is
  /// order by `name` in ascending order.
  public var orderBy: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ListEndpointsRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListEndpointsRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let parent = CodingKeys(stringValue: "parent")
    static let pageSize = CodingKeys(stringValue: "pageSize")
    static let pageToken = CodingKeys(stringValue: "pageToken")
    static let filter = CodingKeys(stringValue: "filter")
    static let orderBy = CodingKeys(stringValue: "orderBy")

    static let _knownKeys: Set<Swift.String> = [
      "parent",
      "pageSize",
      "pageToken",
      "filter",
      "orderBy",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .parent) {
      self.parent = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .pageSize) {
      self.pageSize = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .pageToken) {
      self.pageToken = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .filter) {
      self.filter = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .orderBy) {
      self.orderBy = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.parent, forKey: .parent)
    try container.encode(self.pageSize, forKey: .pageSize)
    try container.encode(self.pageToken, forKey: .pageToken)
    try container.encode(self.filter, forKey: .filter)
    try container.encode(self.orderBy, forKey: .orderBy)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.servicedirectory.v1.ListEndpointsRequest"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
