// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleCloudWkt
import GoogleCloudGax

/// Service Directory API for looking up service data at runtime.
///
/// @Snippet(path: "LookupServiceQuickstart")
public class LookupServiceClient: Clients.LookupServiceProtocol {
  let inner: any Clients.LookupServiceStub

  /// Creates a new `LookupServiceClient` instance.
  public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
    var inner: any Clients.LookupServiceStub = try Clients.LookupServiceTransport(options)
    inner = Clients.LookupServiceRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.LookupServiceLogging(inner, logger: logger)
    }
    self.inner = inner
  }

  /// Returns a [service][google.cloud.servicedirectory.v1.Service] and its
  /// associated endpoints.
  /// Resolving a service is not considered an active developer method.
  ///
  /// [google.cloud.servicedirectory.v1.Service]: <doc:Service>
  ///
  /// @Snippet(path: "LookupService_ResolveService")
  public func resolveService(
    request: ResolveServiceRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudServiceDirectoryV1.ResolveServiceResponse {
    try await self.inner.resolveService(request: request, options: options)
  }

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "LookupService_ListLocations")
  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    try await self.inner.listLocations(request: request, options: options)
  }

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "LookupService_ListLocations")
  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listLocations(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets information about a location.
  ///
  /// @Snippet(path: "LookupService_GetLocation")
  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    try await self.inner.getLocation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `LookupServiceClient`.
  ///
  /// To mock `LookupServiceClient` change your functions to receive
  /// `some LookupServiceProtocol` or `any LookupServiceProtocol`
  /// and pass a mock implementation in your tests.
  public protocol LookupServiceProtocol {
    /// See `LookupServiceClient.resolveService`.
    func resolveService(request: ResolveServiceRequest) async throws
      -> GoogleCloudServiceDirectoryV1.ResolveServiceResponse

    /// See `LookupServiceClient.listLocations`.
    func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
      -> GoogleCloudLocation.ListLocationsResponse

    /// See `LookupServiceClient.listLocations`.
    func listLocations(
      byItem: GoogleCloudLocation.ListLocationsRequest
    ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error>

    /// See `LookupServiceClient.getLocation`.
    func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
      -> GoogleCloudLocation.Location

    /// See `LookupServiceClient.resolveService`.
    func resolveService(
      request: ResolveServiceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudServiceDirectoryV1.ResolveServiceResponse

    /// See `LookupServiceClient.listLocations`.
    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    /// See `LookupServiceClient.listLocations`.
    func listLocations(
      byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error>

    /// See `LookupServiceClient.getLocation`.
    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location
  }
}

// Default implementations
extension Clients.LookupServiceProtocol {
  public func resolveService(request: ResolveServiceRequest) async throws
    -> GoogleCloudServiceDirectoryV1.ResolveServiceResponse
  {
    try await self.resolveService(request: request, options: .init())
  }

  public func resolveService(
    request: ResolveServiceRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudServiceDirectoryV1.ResolveServiceResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
    -> GoogleCloudLocation.ListLocationsResponse
  {
    try await self.listLocations(request: request, options: .init())
  }

  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    try self.listLocations(byItem: byItem, options: .init())
  }

  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
    -> GoogleCloudLocation.Location
  {
    try await self.getLocation(request: request, options: .init())
  }

  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    throw GoogleCloudGax.RequestError.unimplemented
  }
}
