// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleIAMV1
import GoogleWKT
import GoogleGax
import struct Logging.Logger

extension Clients {
  final class RegistrationServiceLogging: RegistrationServiceStub {
    let inner: any RegistrationServiceStub
    let logger: Logger

    public init(_ inner: any RegistrationServiceStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "google-cloud-servicedirectory-v1"
      logger[metadataKey: "gcp.client.service"] = "servicedirectory"
      logger[metadataKey: "gcp.experimental.swift.client"] = "RegistrationService"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func createNamespace(
      request: CreateNamespaceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudServiceDirectoryV1.Namespace {
      try await self._intercept(
        request: request,
        options: options,
        name: "createNamespace",
        action: {
          (r: CreateNamespaceRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudServiceDirectoryV1.Namespace
          in
          return try await self.inner.createNamespace(request: r, options: o)
        })
    }

    public func listNamespaces(
      request: ListNamespacesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudServiceDirectoryV1.ListNamespacesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listNamespaces",
        action: {
          (r: ListNamespacesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudServiceDirectoryV1.ListNamespacesResponse
          in
          return try await self.inner.listNamespaces(request: r, options: o)
        })
    }

    public func getNamespace(
      request: GetNamespaceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudServiceDirectoryV1.Namespace {
      try await self._intercept(
        request: request,
        options: options,
        name: "getNamespace",
        action: {
          (r: GetNamespaceRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudServiceDirectoryV1.Namespace
          in
          return try await self.inner.getNamespace(request: r, options: o)
        })
    }

    public func updateNamespace(
      request: UpdateNamespaceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudServiceDirectoryV1.Namespace {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateNamespace",
        action: {
          (r: UpdateNamespaceRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudServiceDirectoryV1.Namespace
          in
          return try await self.inner.updateNamespace(request: r, options: o)
        })
    }

    public func deleteNamespace(
      request: DeleteNamespaceRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteNamespace",
        action: { (r: DeleteNamespaceRequest, o: GoogleGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteNamespace(request: r, options: o)
        })
    }

    public func createService(
      request: CreateServiceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudServiceDirectoryV1.Service {
      try await self._intercept(
        request: request,
        options: options,
        name: "createService",
        action: {
          (r: CreateServiceRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudServiceDirectoryV1.Service
          in
          return try await self.inner.createService(request: r, options: o)
        })
    }

    public func listServices(
      request: ListServicesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudServiceDirectoryV1.ListServicesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listServices",
        action: {
          (r: ListServicesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudServiceDirectoryV1.ListServicesResponse
          in
          return try await self.inner.listServices(request: r, options: o)
        })
    }

    public func getService(
      request: GetServiceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudServiceDirectoryV1.Service {
      try await self._intercept(
        request: request,
        options: options,
        name: "getService",
        action: {
          (r: GetServiceRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudServiceDirectoryV1.Service
          in
          return try await self.inner.getService(request: r, options: o)
        })
    }

    public func updateService(
      request: UpdateServiceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudServiceDirectoryV1.Service {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateService",
        action: {
          (r: UpdateServiceRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudServiceDirectoryV1.Service
          in
          return try await self.inner.updateService(request: r, options: o)
        })
    }

    public func deleteService(
      request: DeleteServiceRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteService",
        action: { (r: DeleteServiceRequest, o: GoogleGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteService(request: r, options: o)
        })
    }

    public func createEndpoint(
      request: CreateEndpointRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudServiceDirectoryV1.Endpoint {
      try await self._intercept(
        request: request,
        options: options,
        name: "createEndpoint",
        action: {
          (r: CreateEndpointRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudServiceDirectoryV1.Endpoint
          in
          return try await self.inner.createEndpoint(request: r, options: o)
        })
    }

    public func listEndpoints(
      request: ListEndpointsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudServiceDirectoryV1.ListEndpointsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listEndpoints",
        action: {
          (r: ListEndpointsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudServiceDirectoryV1.ListEndpointsResponse
          in
          return try await self.inner.listEndpoints(request: r, options: o)
        })
    }

    public func getEndpoint(
      request: GetEndpointRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudServiceDirectoryV1.Endpoint {
      try await self._intercept(
        request: request,
        options: options,
        name: "getEndpoint",
        action: {
          (r: GetEndpointRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudServiceDirectoryV1.Endpoint
          in
          return try await self.inner.getEndpoint(request: r, options: o)
        })
    }

    public func updateEndpoint(
      request: UpdateEndpointRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudServiceDirectoryV1.Endpoint {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateEndpoint",
        action: {
          (r: UpdateEndpointRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudServiceDirectoryV1.Endpoint
          in
          return try await self.inner.updateEndpoint(request: r, options: o)
        })
    }

    public func deleteEndpoint(
      request: DeleteEndpointRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteEndpoint",
        action: { (r: DeleteEndpointRequest, o: GoogleGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteEndpoint(request: r, options: o)
        })
    }

    public func getIamPolicy(
      request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy {
      try await self._intercept(
        request: request,
        options: options,
        name: "getIamPolicy",
        action: {
          (r: GoogleIAMV1.GetIamPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIAMV1.Policy
          in
          return try await self.inner.getIamPolicy(request: r, options: o)
        })
    }

    public func setIamPolicy(
      request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy {
      try await self._intercept(
        request: request,
        options: options,
        name: "setIamPolicy",
        action: {
          (r: GoogleIAMV1.SetIamPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIAMV1.Policy
          in
          return try await self.inner.setIamPolicy(request: r, options: o)
        })
    }

    public func testIamPermissions(
      request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.TestIamPermissionsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "testIamPermissions",
        action: {
          (r: GoogleIAMV1.TestIamPermissionsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIAMV1.TestIamPermissionsResponse
          in
          return try await self.inner.testIamPermissions(request: r, options: o)
        })
    }

    public func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listLocations",
        action: {
          (r: GoogleCloudLocation.ListLocationsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudLocation.ListLocationsResponse
          in
          return try await self.inner.listLocations(request: r, options: o)
        })
    }

    public func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location {
      try await self._intercept(
        request: request,
        options: options,
        name: "getLocation",
        action: {
          (r: GoogleCloudLocation.GetLocationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudLocation.Location
          in
          return try await self.inner.getLocation(request: r, options: o)
        })
    }
  }
}
