// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleCloudWkt
import GoogleIAMV1
@_spi(GoogleCloudInternal) import GoogleCloudGax

extension Clients {
  final class RegistrationServiceRetry: RegistrationServiceStub {
    let inner: any RegistrationServiceStub
    let options: GoogleCloudGax.ClientOptions

    public init(_ inner: any RegistrationServiceStub, options: GoogleCloudGax.ClientOptions) {
      self.inner = inner
      self.options = options
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      idempotent: Swift.Bool,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      let loop = GoogleCloudGax._RetryLoop(
        options: options, withDefault: self.options, idempotent: idempotent,
      )
      let attempt = { (attemptTimeout: Swift.Duration?) async throws -> Output in
        var attemptOptions = options
        attemptOptions.attemptTimeout = attemptTimeout
        return try await action(request, attemptOptions)
      }
      return try await loop.run(attempt: attempt)
    }

    public func createNamespace(
      request: CreateNamespaceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudServiceDirectoryV1.Namespace {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateNamespaceRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudServiceDirectoryV1.Namespace
          in
          return try await self.inner.createNamespace(request: r, options: o)
        })
    }

    public func listNamespaces(
      request: ListNamespacesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudServiceDirectoryV1.ListNamespacesResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListNamespacesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudServiceDirectoryV1.ListNamespacesResponse
          in
          return try await self.inner.listNamespaces(request: r, options: o)
        })
    }

    public func getNamespace(
      request: GetNamespaceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudServiceDirectoryV1.Namespace {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetNamespaceRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudServiceDirectoryV1.Namespace
          in
          return try await self.inner.getNamespace(request: r, options: o)
        })
    }

    public func updateNamespace(
      request: UpdateNamespaceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudServiceDirectoryV1.Namespace {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateNamespaceRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudServiceDirectoryV1.Namespace
          in
          return try await self.inner.updateNamespace(request: r, options: o)
        })
    }

    public func deleteNamespace(
      request: DeleteNamespaceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteNamespaceRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteNamespace(request: r, options: o)
        })
    }

    public func createService(
      request: CreateServiceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudServiceDirectoryV1.Service {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateServiceRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudServiceDirectoryV1.Service
          in
          return try await self.inner.createService(request: r, options: o)
        })
    }

    public func listServices(
      request: ListServicesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudServiceDirectoryV1.ListServicesResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListServicesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudServiceDirectoryV1.ListServicesResponse
          in
          return try await self.inner.listServices(request: r, options: o)
        })
    }

    public func getService(
      request: GetServiceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudServiceDirectoryV1.Service {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetServiceRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudServiceDirectoryV1.Service
          in
          return try await self.inner.getService(request: r, options: o)
        })
    }

    public func updateService(
      request: UpdateServiceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudServiceDirectoryV1.Service {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateServiceRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudServiceDirectoryV1.Service
          in
          return try await self.inner.updateService(request: r, options: o)
        })
    }

    public func deleteService(
      request: DeleteServiceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteServiceRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteService(request: r, options: o)
        })
    }

    public func createEndpoint(
      request: CreateEndpointRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudServiceDirectoryV1.Endpoint {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateEndpointRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudServiceDirectoryV1.Endpoint
          in
          return try await self.inner.createEndpoint(request: r, options: o)
        })
    }

    public func listEndpoints(
      request: ListEndpointsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudServiceDirectoryV1.ListEndpointsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListEndpointsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudServiceDirectoryV1.ListEndpointsResponse
          in
          return try await self.inner.listEndpoints(request: r, options: o)
        })
    }

    public func getEndpoint(
      request: GetEndpointRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudServiceDirectoryV1.Endpoint {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetEndpointRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudServiceDirectoryV1.Endpoint
          in
          return try await self.inner.getEndpoint(request: r, options: o)
        })
    }

    public func updateEndpoint(
      request: UpdateEndpointRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudServiceDirectoryV1.Endpoint {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateEndpointRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudServiceDirectoryV1.Endpoint
          in
          return try await self.inner.updateEndpoint(request: r, options: o)
        })
    }

    public func deleteEndpoint(
      request: DeleteEndpointRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteEndpointRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteEndpoint(request: r, options: o)
        })
    }

    public func getIamPolicy(
      request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: GoogleIAMV1.GetIamPolicyRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleIAMV1.Policy
          in
          return try await self.inner.getIamPolicy(request: r, options: o)
        })
    }

    public func setIamPolicy(
      request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: GoogleIAMV1.SetIamPolicyRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleIAMV1.Policy
          in
          return try await self.inner.setIamPolicy(request: r, options: o)
        })
    }

    public func testIamPermissions(
      request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.TestIamPermissionsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: GoogleIAMV1.TestIamPermissionsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleIAMV1.TestIamPermissionsResponse
          in
          return try await self.inner.testIamPermissions(request: r, options: o)
        })
    }

    public func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleCloudLocation.ListLocationsRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleCloudLocation.ListLocationsResponse
          in
          return try await self.inner.listLocations(request: r, options: o)
        })
    }

    public func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleCloudLocation.GetLocationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudLocation.Location
          in
          return try await self.inner.getLocation(request: r, options: o)
        })
    }
  }
}
