// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleCloudWKT
import GoogleIAMV1
import GoogleCloudGax

/// Service Directory API for registering services. It defines the following
/// resource model:
///
/// - The API has a collection of
/// [Namespace][google.cloud.servicedirectory.v1.Namespace]
/// resources, named `projects/*/locations/*/namespaces/*`.
///
/// - Each Namespace has a collection of
/// [Service][google.cloud.servicedirectory.v1.Service] resources, named
/// `projects/*/locations/*/namespaces/*/services/*`.
///
/// - Each Service has a collection of
/// [Endpoint][google.cloud.servicedirectory.v1.Endpoint]
/// resources, named
/// `projects/*/locations/*/namespaces/*/services/*/endpoints/*`.
///
/// [google.cloud.servicedirectory.v1.Endpoint]: <doc:Endpoint>
/// [google.cloud.servicedirectory.v1.Namespace]: <doc:Namespace>
/// [google.cloud.servicedirectory.v1.Service]: <doc:Service>
///
/// @Snippet(path: "RegistrationServiceQuickstart")
public final class RegistrationServiceClient: Clients.RegistrationServiceProtocol, Sendable {
  let inner: any Clients.RegistrationServiceStub

  /// Creates a new `RegistrationServiceClient` instance.
  public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
    var inner: any Clients.RegistrationServiceStub = try Clients.RegistrationServiceTransport(
      options)
    inner = Clients.RegistrationServiceRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.RegistrationServiceLogging(inner, logger: logger)
    }
    self.inner = inner
  }

  /// Creates a namespace, and returns the new namespace.
  ///
  /// @Snippet(path: "RegistrationService_CreateNamespace")
  public func createNamespace(
    request: CreateNamespaceRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudServiceDirectoryV1.Namespace {
    try await self.inner.createNamespace(request: request, options: options)
  }

  /// Lists all namespaces.
  ///
  /// @Snippet(path: "RegistrationService_ListNamespaces")
  public func listNamespaces(
    request: ListNamespacesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudServiceDirectoryV1.ListNamespacesResponse {
    try await self.inner.listNamespaces(request: request, options: options)
  }

  /// Lists all namespaces.
  ///
  /// @Snippet(path: "RegistrationService_ListNamespaces")
  public func listNamespaces(
    byItem: ListNamespacesRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Namespace, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudServiceDirectoryV1.ListNamespacesResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listNamespaces(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets a namespace.
  ///
  /// @Snippet(path: "RegistrationService_GetNamespace")
  public func getNamespace(
    request: GetNamespaceRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudServiceDirectoryV1.Namespace {
    try await self.inner.getNamespace(request: request, options: options)
  }

  /// Updates a namespace.
  ///
  /// @Snippet(path: "RegistrationService_UpdateNamespace")
  public func updateNamespace(
    request: UpdateNamespaceRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudServiceDirectoryV1.Namespace {
    try await self.inner.updateNamespace(request: request, options: options)
  }

  /// Deletes a namespace. This also deletes all services and endpoints in
  /// the namespace.
  ///
  /// @Snippet(path: "RegistrationService_DeleteNamespace")
  public func deleteNamespace(
    request: DeleteNamespaceRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.deleteNamespace(request: request, options: options)
  }

  /// Creates a service, and returns the new service.
  ///
  /// @Snippet(path: "RegistrationService_CreateService")
  public func createService(
    request: CreateServiceRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudServiceDirectoryV1.Service {
    try await self.inner.createService(request: request, options: options)
  }

  /// Lists all services belonging to a namespace.
  ///
  /// @Snippet(path: "RegistrationService_ListServices")
  public func listServices(
    request: ListServicesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudServiceDirectoryV1.ListServicesResponse {
    try await self.inner.listServices(request: request, options: options)
  }

  /// Lists all services belonging to a namespace.
  ///
  /// @Snippet(path: "RegistrationService_ListServices")
  public func listServices(
    byItem: ListServicesRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Service, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudServiceDirectoryV1.ListServicesResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listServices(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets a service.
  ///
  /// @Snippet(path: "RegistrationService_GetService")
  public func getService(
    request: GetServiceRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudServiceDirectoryV1.Service {
    try await self.inner.getService(request: request, options: options)
  }

  /// Updates a service.
  ///
  /// @Snippet(path: "RegistrationService_UpdateService")
  public func updateService(
    request: UpdateServiceRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudServiceDirectoryV1.Service {
    try await self.inner.updateService(request: request, options: options)
  }

  /// Deletes a service. This also deletes all endpoints associated with
  /// the service.
  ///
  /// @Snippet(path: "RegistrationService_DeleteService")
  public func deleteService(
    request: DeleteServiceRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.deleteService(request: request, options: options)
  }

  /// Creates an endpoint, and returns the new endpoint.
  ///
  /// @Snippet(path: "RegistrationService_CreateEndpoint")
  public func createEndpoint(
    request: CreateEndpointRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudServiceDirectoryV1.Endpoint {
    try await self.inner.createEndpoint(request: request, options: options)
  }

  /// Lists all endpoints.
  ///
  /// @Snippet(path: "RegistrationService_ListEndpoints")
  public func listEndpoints(
    request: ListEndpointsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudServiceDirectoryV1.ListEndpointsResponse {
    try await self.inner.listEndpoints(request: request, options: options)
  }

  /// Lists all endpoints.
  ///
  /// @Snippet(path: "RegistrationService_ListEndpoints")
  public func listEndpoints(
    byItem: ListEndpointsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Endpoint, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudServiceDirectoryV1.ListEndpointsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listEndpoints(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets an endpoint.
  ///
  /// @Snippet(path: "RegistrationService_GetEndpoint")
  public func getEndpoint(
    request: GetEndpointRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudServiceDirectoryV1.Endpoint {
    try await self.inner.getEndpoint(request: request, options: options)
  }

  /// Updates an endpoint.
  ///
  /// @Snippet(path: "RegistrationService_UpdateEndpoint")
  public func updateEndpoint(
    request: UpdateEndpointRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudServiceDirectoryV1.Endpoint {
    try await self.inner.updateEndpoint(request: request, options: options)
  }

  /// Deletes an endpoint.
  ///
  /// @Snippet(path: "RegistrationService_DeleteEndpoint")
  public func deleteEndpoint(
    request: DeleteEndpointRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.deleteEndpoint(request: request, options: options)
  }

  /// Gets the IAM Policy for a resource (namespace or service only).
  ///
  /// @Snippet(path: "RegistrationService_GetIamPolicy")
  public func getIamPolicy(
    request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleIAMV1.Policy {
    try await self.inner.getIamPolicy(request: request, options: options)
  }

  /// Sets the IAM Policy for a resource (namespace or service only).
  ///
  /// @Snippet(path: "RegistrationService_SetIamPolicy")
  public func setIamPolicy(
    request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleIAMV1.Policy {
    try await self.inner.setIamPolicy(request: request, options: options)
  }

  /// Tests IAM permissions for a resource (namespace or service only).
  ///
  /// @Snippet(path: "RegistrationService_TestIamPermissions")
  public func testIamPermissions(
    request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleIAMV1.TestIamPermissionsResponse {
    try await self.inner.testIamPermissions(request: request, options: options)
  }

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "RegistrationService_ListLocations")
  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    try await self.inner.listLocations(request: request, options: options)
  }

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "RegistrationService_ListLocations")
  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listLocations(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets information about a location.
  ///
  /// @Snippet(path: "RegistrationService_GetLocation")
  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    try await self.inner.getLocation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `RegistrationServiceClient`.
  ///
  /// To mock `RegistrationServiceClient` change your functions to receive
  /// `some RegistrationServiceProtocol` or `any RegistrationServiceProtocol`
  /// and pass a mock implementation in your tests.
  public protocol RegistrationServiceProtocol {
    /// See `RegistrationServiceClient.createNamespace`.
    func createNamespace(request: CreateNamespaceRequest) async throws
      -> GoogleCloudServiceDirectoryV1.Namespace

    /// See `RegistrationServiceClient.createNamespace`.
    func createNamespace(
      parent: Swift.String,
      namespace: Namespace?,
      namespaceId: Swift.String,
    ) async throws -> GoogleCloudServiceDirectoryV1.Namespace

    /// See `RegistrationServiceClient.listNamespaces`.
    func listNamespaces(request: ListNamespacesRequest) async throws
      -> GoogleCloudServiceDirectoryV1.ListNamespacesResponse

    /// See `RegistrationServiceClient.listNamespaces`.
    func listNamespaces(
      byItem: ListNamespacesRequest
    ) throws -> any AsyncSequence<Namespace, Swift.Error>

    /// See `RegistrationServiceClient.listNamespaces`.
    func listNamespaces(
      parent: Swift.String,
    ) throws -> any AsyncSequence<Namespace, Swift.Error>

    /// See `RegistrationServiceClient.getNamespace`.
    func getNamespace(request: GetNamespaceRequest) async throws
      -> GoogleCloudServiceDirectoryV1.Namespace

    /// See `RegistrationServiceClient.getNamespace`.
    func getNamespace(
      name: Swift.String,
    ) async throws -> GoogleCloudServiceDirectoryV1.Namespace

    /// See `RegistrationServiceClient.updateNamespace`.
    func updateNamespace(request: UpdateNamespaceRequest) async throws
      -> GoogleCloudServiceDirectoryV1.Namespace

    /// See `RegistrationServiceClient.updateNamespace`.
    func updateNamespace(
      namespace: Namespace?,
      updateMask: GoogleCloudWKT.FieldMask?,
    ) async throws -> GoogleCloudServiceDirectoryV1.Namespace

    /// See `RegistrationServiceClient.deleteNamespace`.
    func deleteNamespace(request: DeleteNamespaceRequest) async throws

    /// See `RegistrationServiceClient.deleteNamespace`.
    func deleteNamespace(
      name: Swift.String,
    ) async throws

    /// See `RegistrationServiceClient.createService`.
    func createService(request: CreateServiceRequest) async throws
      -> GoogleCloudServiceDirectoryV1.Service

    /// See `RegistrationServiceClient.createService`.
    func createService(
      parent: Swift.String,
      service: Service?,
      serviceId: Swift.String,
    ) async throws -> GoogleCloudServiceDirectoryV1.Service

    /// See `RegistrationServiceClient.listServices`.
    func listServices(request: ListServicesRequest) async throws
      -> GoogleCloudServiceDirectoryV1.ListServicesResponse

    /// See `RegistrationServiceClient.listServices`.
    func listServices(
      byItem: ListServicesRequest
    ) throws -> any AsyncSequence<Service, Swift.Error>

    /// See `RegistrationServiceClient.listServices`.
    func listServices(
      parent: Swift.String,
    ) throws -> any AsyncSequence<Service, Swift.Error>

    /// See `RegistrationServiceClient.getService`.
    func getService(request: GetServiceRequest) async throws
      -> GoogleCloudServiceDirectoryV1.Service

    /// See `RegistrationServiceClient.getService`.
    func getService(
      name: Swift.String,
    ) async throws -> GoogleCloudServiceDirectoryV1.Service

    /// See `RegistrationServiceClient.updateService`.
    func updateService(request: UpdateServiceRequest) async throws
      -> GoogleCloudServiceDirectoryV1.Service

    /// See `RegistrationServiceClient.updateService`.
    func updateService(
      service: Service?,
      updateMask: GoogleCloudWKT.FieldMask?,
    ) async throws -> GoogleCloudServiceDirectoryV1.Service

    /// See `RegistrationServiceClient.deleteService`.
    func deleteService(request: DeleteServiceRequest) async throws

    /// See `RegistrationServiceClient.deleteService`.
    func deleteService(
      name: Swift.String,
    ) async throws

    /// See `RegistrationServiceClient.createEndpoint`.
    func createEndpoint(request: CreateEndpointRequest) async throws
      -> GoogleCloudServiceDirectoryV1.Endpoint

    /// See `RegistrationServiceClient.createEndpoint`.
    func createEndpoint(
      parent: Swift.String,
      endpoint: Endpoint?,
      endpointId: Swift.String,
    ) async throws -> GoogleCloudServiceDirectoryV1.Endpoint

    /// See `RegistrationServiceClient.listEndpoints`.
    func listEndpoints(request: ListEndpointsRequest) async throws
      -> GoogleCloudServiceDirectoryV1.ListEndpointsResponse

    /// See `RegistrationServiceClient.listEndpoints`.
    func listEndpoints(
      byItem: ListEndpointsRequest
    ) throws -> any AsyncSequence<Endpoint, Swift.Error>

    /// See `RegistrationServiceClient.listEndpoints`.
    func listEndpoints(
      parent: Swift.String,
    ) throws -> any AsyncSequence<Endpoint, Swift.Error>

    /// See `RegistrationServiceClient.getEndpoint`.
    func getEndpoint(request: GetEndpointRequest) async throws
      -> GoogleCloudServiceDirectoryV1.Endpoint

    /// See `RegistrationServiceClient.getEndpoint`.
    func getEndpoint(
      name: Swift.String,
    ) async throws -> GoogleCloudServiceDirectoryV1.Endpoint

    /// See `RegistrationServiceClient.updateEndpoint`.
    func updateEndpoint(request: UpdateEndpointRequest) async throws
      -> GoogleCloudServiceDirectoryV1.Endpoint

    /// See `RegistrationServiceClient.updateEndpoint`.
    func updateEndpoint(
      endpoint: Endpoint?,
      updateMask: GoogleCloudWKT.FieldMask?,
    ) async throws -> GoogleCloudServiceDirectoryV1.Endpoint

    /// See `RegistrationServiceClient.deleteEndpoint`.
    func deleteEndpoint(request: DeleteEndpointRequest) async throws

    /// See `RegistrationServiceClient.deleteEndpoint`.
    func deleteEndpoint(
      name: Swift.String,
    ) async throws

    /// See `RegistrationServiceClient.getIamPolicy`.
    func getIamPolicy(request: GoogleIAMV1.GetIamPolicyRequest) async throws -> GoogleIAMV1.Policy

    /// See `RegistrationServiceClient.setIamPolicy`.
    func setIamPolicy(request: GoogleIAMV1.SetIamPolicyRequest) async throws -> GoogleIAMV1.Policy

    /// See `RegistrationServiceClient.testIamPermissions`.
    func testIamPermissions(request: GoogleIAMV1.TestIamPermissionsRequest) async throws
      -> GoogleIAMV1.TestIamPermissionsResponse

    /// See `RegistrationServiceClient.listLocations`.
    func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
      -> GoogleCloudLocation.ListLocationsResponse

    /// See `RegistrationServiceClient.listLocations`.
    func listLocations(
      byItem: GoogleCloudLocation.ListLocationsRequest
    ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error>

    /// See `RegistrationServiceClient.getLocation`.
    func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
      -> GoogleCloudLocation.Location

    /// See `RegistrationServiceClient.createNamespace`.
    func createNamespace(
      request: CreateNamespaceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudServiceDirectoryV1.Namespace

    /// See `RegistrationServiceClient.listNamespaces`.
    func listNamespaces(
      request: ListNamespacesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudServiceDirectoryV1.ListNamespacesResponse

    /// See `RegistrationServiceClient.listNamespaces`.
    func listNamespaces(
      byItem: ListNamespacesRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<Namespace, Swift.Error>

    /// See `RegistrationServiceClient.getNamespace`.
    func getNamespace(
      request: GetNamespaceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudServiceDirectoryV1.Namespace

    /// See `RegistrationServiceClient.updateNamespace`.
    func updateNamespace(
      request: UpdateNamespaceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudServiceDirectoryV1.Namespace

    /// See `RegistrationServiceClient.deleteNamespace`.
    func deleteNamespace(
      request: DeleteNamespaceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    /// See `RegistrationServiceClient.createService`.
    func createService(
      request: CreateServiceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudServiceDirectoryV1.Service

    /// See `RegistrationServiceClient.listServices`.
    func listServices(
      request: ListServicesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudServiceDirectoryV1.ListServicesResponse

    /// See `RegistrationServiceClient.listServices`.
    func listServices(
      byItem: ListServicesRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<Service, Swift.Error>

    /// See `RegistrationServiceClient.getService`.
    func getService(
      request: GetServiceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudServiceDirectoryV1.Service

    /// See `RegistrationServiceClient.updateService`.
    func updateService(
      request: UpdateServiceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudServiceDirectoryV1.Service

    /// See `RegistrationServiceClient.deleteService`.
    func deleteService(
      request: DeleteServiceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    /// See `RegistrationServiceClient.createEndpoint`.
    func createEndpoint(
      request: CreateEndpointRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudServiceDirectoryV1.Endpoint

    /// See `RegistrationServiceClient.listEndpoints`.
    func listEndpoints(
      request: ListEndpointsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudServiceDirectoryV1.ListEndpointsResponse

    /// See `RegistrationServiceClient.listEndpoints`.
    func listEndpoints(
      byItem: ListEndpointsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<Endpoint, Swift.Error>

    /// See `RegistrationServiceClient.getEndpoint`.
    func getEndpoint(
      request: GetEndpointRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudServiceDirectoryV1.Endpoint

    /// See `RegistrationServiceClient.updateEndpoint`.
    func updateEndpoint(
      request: UpdateEndpointRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudServiceDirectoryV1.Endpoint

    /// See `RegistrationServiceClient.deleteEndpoint`.
    func deleteEndpoint(
      request: DeleteEndpointRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    /// See `RegistrationServiceClient.getIamPolicy`.
    func getIamPolicy(
      request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    /// See `RegistrationServiceClient.setIamPolicy`.
    func setIamPolicy(
      request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    /// See `RegistrationServiceClient.testIamPermissions`.
    func testIamPermissions(
      request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.TestIamPermissionsResponse

    /// See `RegistrationServiceClient.listLocations`.
    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    /// See `RegistrationServiceClient.listLocations`.
    func listLocations(
      byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error>

    /// See `RegistrationServiceClient.getLocation`.
    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location
  }
}

// Default implementations
extension Clients.RegistrationServiceProtocol {
  public func createNamespace(request: CreateNamespaceRequest) async throws
    -> GoogleCloudServiceDirectoryV1.Namespace
  {
    try await self.createNamespace(request: request, options: .init())
  }

  public func createNamespace(
    request: CreateNamespaceRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudServiceDirectoryV1.Namespace {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createNamespace(
    parent: Swift.String,
    namespace: Namespace?,
    namespaceId: Swift.String,
  ) async throws -> GoogleCloudServiceDirectoryV1.Namespace {
    let request = CreateNamespaceRequest().with {
      $0.parent = parent
      $0.namespace = namespace
      $0.namespaceId = namespaceId
    }
    return try await self.createNamespace(request: request)
  }

  public func listNamespaces(request: ListNamespacesRequest) async throws
    -> GoogleCloudServiceDirectoryV1.ListNamespacesResponse
  {
    try await self.listNamespaces(request: request, options: .init())
  }

  public func listNamespaces(
    request: ListNamespacesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudServiceDirectoryV1.ListNamespacesResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listNamespaces(
    byItem: ListNamespacesRequest
  ) throws -> any AsyncSequence<Namespace, Swift.Error> {
    try self.listNamespaces(byItem: byItem, options: .init())
  }

  public func listNamespaces(
    byItem: ListNamespacesRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Namespace, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudServiceDirectoryV1.ListNamespacesResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listNamespaces(
    parent: Swift.String,
  ) throws -> any AsyncSequence<Namespace, Swift.Error> {
    let request = ListNamespacesRequest().with {
      $0.parent = parent
    }
    return try self.listNamespaces(byItem: request)
  }

  public func getNamespace(request: GetNamespaceRequest) async throws
    -> GoogleCloudServiceDirectoryV1.Namespace
  {
    try await self.getNamespace(request: request, options: .init())
  }

  public func getNamespace(
    request: GetNamespaceRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudServiceDirectoryV1.Namespace {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getNamespace(
    name: Swift.String,
  ) async throws -> GoogleCloudServiceDirectoryV1.Namespace {
    let request = GetNamespaceRequest().with {
      $0.name = name
    }
    return try await self.getNamespace(request: request)
  }

  public func updateNamespace(request: UpdateNamespaceRequest) async throws
    -> GoogleCloudServiceDirectoryV1.Namespace
  {
    try await self.updateNamespace(request: request, options: .init())
  }

  public func updateNamespace(
    request: UpdateNamespaceRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudServiceDirectoryV1.Namespace {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func updateNamespace(
    namespace: Namespace?,
    updateMask: GoogleCloudWKT.FieldMask?,
  ) async throws -> GoogleCloudServiceDirectoryV1.Namespace {
    let request = UpdateNamespaceRequest().with {
      $0.namespace = namespace
      $0.updateMask = updateMask
    }
    return try await self.updateNamespace(request: request)
  }

  public func deleteNamespace(request: DeleteNamespaceRequest) async throws {
    try await self.deleteNamespace(request: request, options: .init())
  }

  public func deleteNamespace(
    request: DeleteNamespaceRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteNamespace(
    name: Swift.String,
  ) async throws {
    let request = DeleteNamespaceRequest().with {
      $0.name = name
    }
    try await self.deleteNamespace(request: request)
  }

  public func createService(request: CreateServiceRequest) async throws
    -> GoogleCloudServiceDirectoryV1.Service
  {
    try await self.createService(request: request, options: .init())
  }

  public func createService(
    request: CreateServiceRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudServiceDirectoryV1.Service {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createService(
    parent: Swift.String,
    service: Service?,
    serviceId: Swift.String,
  ) async throws -> GoogleCloudServiceDirectoryV1.Service {
    let request = CreateServiceRequest().with {
      $0.parent = parent
      $0.service = service
      $0.serviceId = serviceId
    }
    return try await self.createService(request: request)
  }

  public func listServices(request: ListServicesRequest) async throws
    -> GoogleCloudServiceDirectoryV1.ListServicesResponse
  {
    try await self.listServices(request: request, options: .init())
  }

  public func listServices(
    request: ListServicesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudServiceDirectoryV1.ListServicesResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listServices(
    byItem: ListServicesRequest
  ) throws -> any AsyncSequence<Service, Swift.Error> {
    try self.listServices(byItem: byItem, options: .init())
  }

  public func listServices(
    byItem: ListServicesRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Service, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudServiceDirectoryV1.ListServicesResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listServices(
    parent: Swift.String,
  ) throws -> any AsyncSequence<Service, Swift.Error> {
    let request = ListServicesRequest().with {
      $0.parent = parent
    }
    return try self.listServices(byItem: request)
  }

  public func getService(request: GetServiceRequest) async throws
    -> GoogleCloudServiceDirectoryV1.Service
  {
    try await self.getService(request: request, options: .init())
  }

  public func getService(
    request: GetServiceRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudServiceDirectoryV1.Service {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getService(
    name: Swift.String,
  ) async throws -> GoogleCloudServiceDirectoryV1.Service {
    let request = GetServiceRequest().with {
      $0.name = name
    }
    return try await self.getService(request: request)
  }

  public func updateService(request: UpdateServiceRequest) async throws
    -> GoogleCloudServiceDirectoryV1.Service
  {
    try await self.updateService(request: request, options: .init())
  }

  public func updateService(
    request: UpdateServiceRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudServiceDirectoryV1.Service {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func updateService(
    service: Service?,
    updateMask: GoogleCloudWKT.FieldMask?,
  ) async throws -> GoogleCloudServiceDirectoryV1.Service {
    let request = UpdateServiceRequest().with {
      $0.service = service
      $0.updateMask = updateMask
    }
    return try await self.updateService(request: request)
  }

  public func deleteService(request: DeleteServiceRequest) async throws {
    try await self.deleteService(request: request, options: .init())
  }

  public func deleteService(
    request: DeleteServiceRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteService(
    name: Swift.String,
  ) async throws {
    let request = DeleteServiceRequest().with {
      $0.name = name
    }
    try await self.deleteService(request: request)
  }

  public func createEndpoint(request: CreateEndpointRequest) async throws
    -> GoogleCloudServiceDirectoryV1.Endpoint
  {
    try await self.createEndpoint(request: request, options: .init())
  }

  public func createEndpoint(
    request: CreateEndpointRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudServiceDirectoryV1.Endpoint {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createEndpoint(
    parent: Swift.String,
    endpoint: Endpoint?,
    endpointId: Swift.String,
  ) async throws -> GoogleCloudServiceDirectoryV1.Endpoint {
    let request = CreateEndpointRequest().with {
      $0.parent = parent
      $0.endpoint = endpoint
      $0.endpointId = endpointId
    }
    return try await self.createEndpoint(request: request)
  }

  public func listEndpoints(request: ListEndpointsRequest) async throws
    -> GoogleCloudServiceDirectoryV1.ListEndpointsResponse
  {
    try await self.listEndpoints(request: request, options: .init())
  }

  public func listEndpoints(
    request: ListEndpointsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudServiceDirectoryV1.ListEndpointsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listEndpoints(
    byItem: ListEndpointsRequest
  ) throws -> any AsyncSequence<Endpoint, Swift.Error> {
    try self.listEndpoints(byItem: byItem, options: .init())
  }

  public func listEndpoints(
    byItem: ListEndpointsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Endpoint, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudServiceDirectoryV1.ListEndpointsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listEndpoints(
    parent: Swift.String,
  ) throws -> any AsyncSequence<Endpoint, Swift.Error> {
    let request = ListEndpointsRequest().with {
      $0.parent = parent
    }
    return try self.listEndpoints(byItem: request)
  }

  public func getEndpoint(request: GetEndpointRequest) async throws
    -> GoogleCloudServiceDirectoryV1.Endpoint
  {
    try await self.getEndpoint(request: request, options: .init())
  }

  public func getEndpoint(
    request: GetEndpointRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudServiceDirectoryV1.Endpoint {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getEndpoint(
    name: Swift.String,
  ) async throws -> GoogleCloudServiceDirectoryV1.Endpoint {
    let request = GetEndpointRequest().with {
      $0.name = name
    }
    return try await self.getEndpoint(request: request)
  }

  public func updateEndpoint(request: UpdateEndpointRequest) async throws
    -> GoogleCloudServiceDirectoryV1.Endpoint
  {
    try await self.updateEndpoint(request: request, options: .init())
  }

  public func updateEndpoint(
    request: UpdateEndpointRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudServiceDirectoryV1.Endpoint {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func updateEndpoint(
    endpoint: Endpoint?,
    updateMask: GoogleCloudWKT.FieldMask?,
  ) async throws -> GoogleCloudServiceDirectoryV1.Endpoint {
    let request = UpdateEndpointRequest().with {
      $0.endpoint = endpoint
      $0.updateMask = updateMask
    }
    return try await self.updateEndpoint(request: request)
  }

  public func deleteEndpoint(request: DeleteEndpointRequest) async throws {
    try await self.deleteEndpoint(request: request, options: .init())
  }

  public func deleteEndpoint(
    request: DeleteEndpointRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteEndpoint(
    name: Swift.String,
  ) async throws {
    let request = DeleteEndpointRequest().with {
      $0.name = name
    }
    try await self.deleteEndpoint(request: request)
  }

  public func getIamPolicy(request: GoogleIAMV1.GetIamPolicyRequest) async throws
    -> GoogleIAMV1.Policy
  {
    try await self.getIamPolicy(request: request, options: .init())
  }

  public func getIamPolicy(
    request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleIAMV1.Policy {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func setIamPolicy(request: GoogleIAMV1.SetIamPolicyRequest) async throws
    -> GoogleIAMV1.Policy
  {
    try await self.setIamPolicy(request: request, options: .init())
  }

  public func setIamPolicy(
    request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleIAMV1.Policy {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func testIamPermissions(request: GoogleIAMV1.TestIamPermissionsRequest) async throws
    -> GoogleIAMV1.TestIamPermissionsResponse
  {
    try await self.testIamPermissions(request: request, options: .init())
  }

  public func testIamPermissions(
    request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleIAMV1.TestIamPermissionsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
    -> GoogleCloudLocation.ListLocationsResponse
  {
    try await self.listLocations(request: request, options: .init())
  }

  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    try self.listLocations(byItem: byItem, options: .init())
  }

  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
    -> GoogleCloudLocation.Location
  {
    try await self.getLocation(request: request, options: .init())
  }

  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    throw GoogleCloudGax.RequestError.unimplemented
  }
}
