// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// An individual service. A service contains a name and optional metadata.
/// A service must exist before
/// [endpoints][google.cloud.servicedirectory.v1.Endpoint] can be
/// added to it.
///
/// [google.cloud.servicedirectory.v1.Endpoint]: <doc:Endpoint>
public struct Service: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Immutable. The resource name for the service in the format
  /// `projects/*/locations/*/namespaces/*/services/*`.
  public var name: Swift.String = Swift.String()

  /// Optional. Annotations for the service. This data can be consumed by service
  /// clients.
  ///
  /// Restrictions:
  ///
  /// *   The entire annotations dictionary may contain up to 2000 characters,
  ///     spread accoss all key-value pairs. Annotations that go beyond this
  ///     limit are rejected
  /// *   Valid annotation keys have two segments: an optional prefix and name,
  ///     separated by a slash (/). The name segment is required and must be 63
  ///     characters or less, beginning and ending with an alphanumeric character
  ///     ([a-z0-9A-Z]) with dashes (-), underscores (_), dots (.), and
  ///     alphanumerics between. The prefix is optional. If specified, the prefix
  ///     must be a DNS subdomain: a series of DNS labels separated by dots (.),
  ///     not longer than 253 characters in total, followed by a slash (/).
  ///     Annotations that fails to meet these requirements are rejected
  ///
  /// Note: This field is equivalent to the `metadata` field in the v1beta1 API.
  /// They have the same syntax and read/write to the same location in Service
  /// Directory.
  public var annotations: [Swift.String: Swift.String] = [:]

  /// Output only. Endpoints associated with this service. Returned on
  /// [LookupService.ResolveService][google.cloud.servicedirectory.v1.LookupService.ResolveService].
  /// Control plane clients should use
  /// [RegistrationService.ListEndpoints][google.cloud.servicedirectory.v1.RegistrationService.ListEndpoints].
  ///
  /// [google.cloud.servicedirectory.v1.LookupService.ResolveService]: <doc:LookupServiceClient/resolveService(request:options:)>
  /// [google.cloud.servicedirectory.v1.RegistrationService.ListEndpoints]: <doc:RegistrationServiceClient/listEndpoints(request:options:)>
  public var endpoints: [Endpoint] = []

  /// Output only. The globally unique identifier of the service in the UUID4
  /// format.
  public var uid: Swift.String = Swift.String()

  /// Initialize a new instance of `Service`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Service().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.servicedirectory.v1.Service"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
